# Generated by Django 4.1.5 on 2023-05-28 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_address_teacher_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='skills',
            new_name='adress',
        ),
    ]
