# Generated by Django 4.1.5 on 2023-06-29 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_skills_teacher_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='adress',
            new_name='skills',
        ),
    ]
